config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/index'
  resources :habits do
    resources :logs
  end
  root 'welcome#index'
end

app/models/action.rb
class Action < ApplicationRecord
  belongs_to :habit
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/habit.rb
class Habit < ApplicationRecord
  attribute :last_reset, default: Time.now
  validates :name, presence: true
  validates :positive, inclusion: { in: [true, false] }

  has_many :actions, dependent: :destroy
  has_many :logs, dependent: :destroy
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :habit
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: %i[show edit update destroy]

  # GET /habits
  # GET /habits.json
  def index
    @habits = Habit.all
  end

  # GET /habits/1
  # GET /habits/1.json
  def show
    @habit = Habit.find(params[:id])
  end

  # GET /habits/new
  def new
    @habit = Habit.new
    @initial_actions = %i[obvious attractive easy satisfying].map { |key| { key: key } }
  end

  # GET /habits/1/edit
  def edit; end

  # POST /habits
  # POST /habits.json
  def create
    @habit = Habit.new(habit_params)
    respond_to do |format|
      if @habit.save
        actions_hash = params[:actions]
        actions_hash&.each do |key, action|
          @habit.actions.create(key: key, description: action[:description], done: action[:done])
        end
        format.html { redirect_to habits_path, notice: 'Habit was successfully created.' }
        format.json { render :show, status: :created, location: @habit }
      else
        @habit.errors.full_messages.each do |error|
          puts error
        end
        format.html { render 'new' }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habits/1
  def update
    respond_to do |format|
      if @habit.update(habit_params)
        # iterate through and update actions if they exist. Not super efficient
        params[:actions]&.each do |key, action|
          puts('updating action')
          action_to_update = @habit.actions.find_by(key: key)
          action_to_update.update(description: action[:description], done: action[:done])
        end
        format.html { redirect_to habits_path, notice: 'Habit was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /habits/1
  # DELETE /habits/1.json
  def destroy
    @habit.destroy
    respond_to do |format|
      format.html { redirect_to habits_url, notice: 'Habit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_habit
    @habit = Habit.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def habit_params
    params.require(:habit).permit(:name, :positive, :last_reset)
  end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  def show
    @habit = Habit.find(params[:habit_id])
    @log = @habit.logs.find(params[:id])
  end

  def new
    @habit = Habit.find(params[:habit_id])
  end

  def create
    @habit = Habit.find(params[:habit_id])
    @habit.logs.create(log_params)
    redirect_to @habit
  end

  private

  def log_params
    params.require(:log).permit(:text)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
require 'date'

module HabitsHelper
  def days_since(datetime)
    current_date = Time.now.to_date
    dt_parsed = Date.parse(datetime.to_s)

    num_days = current_date.mjd - dt_parsed.mjd

    "#{num_days} #{'day'.pluralize(num_days)}"
  end

  def habit_type(positive)
    positive ? :Building : :Breaking
  end

  def fraction_completed(actions)
    action_done_count = 0
    nonempty_action_count = 0
    actions.each do |action|
      next if action[:description].to_s.strip.empty?

      nonempty_action_count += 1
      action_done_count += 1 if action[:done]
    end
    "#{action_done_count} / #{nonempty_action_count}"
  end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/habits/_form.html.erb
<%= react_component("habits/Form", { habit: @habit, action: habits_path , authenticity_token: form_authenticity_token}) %>

app/views/habits/edit.html.erb
<%= react_component("habits/Form", { habit: @habit, actions: @habit.actions, errors: @habit.errors, action: habit_path, method: :patch, authenticity_token: form_authenticity_token}) %>

app/views/habits/index.html.erb
<div class="flex flex-col ">
  <div class=" card mx-16 mt-32">
    <p id="notice"><%= notice %></p>
    <h1 class="text-center mb-4">Habits</h1>
    <table class="min-w-full divide-y divide-gray-200 border border-gray-200">
      <thead>
        <tr>
          <th>Description</th>
          <th>Type</th>
          <th>Current Streak</th>
          <th>Actions Completed</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <% @habits.each do |habit| %>
          <tr class="even:bg-gray-100">
            <td class="font-medium"><%= habit.name %></td>
            <td>
              <p class="text-center rounded-full <%=habit.positive ? 'bg-green-200 text-green-600': 'bg-red-200 text-red-600'%>""><%= habit_type(habit.positive)%></p>
            </td>
            <td>
              <div class="flex justify-between w-32">
                <%= days_since(habit.last_reset) %>
                <%= button_to "Reset", habit, params: {:habit => {last_reset: Time.now}}, method: :patch, remote: true,
                  class: "btn-danger btn-small" %>
              </div>
            </td>
            <td><%= fraction_completed(habit.actions) %></td>
            <td><%= link_to 'View', habit, class: "btn-primary btn-small"%></td>
            <td><%= link_to 'Add Log Entry', new_habit_log_path(habit), class: "btn-secondary btn-small" %></td>
            <td><%= link_to 'Destroy', habit, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-danger btn-small"%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <%= link_to 'New Habit', new_habit_path, class: "btn-primary" %>
  </div>
</div>

app/views/habits/new.html.erb
<%= react_component("habits/Form", { habit: @habit, actions: @initial_actions, action: habits_path, errors: @habit.errors, authenticity_token: form_authenticity_token}) %>

app/views/habits/show.html.erb
<div class="max-w-2xl m-auto mt-32 card relative">
  <%= link_to 'Edit', edit_habit_path(@habit), class: "btn-primary absolute top-0 right-0 m-3"%>
  <h1 class="mb-1"><%= @habit.name%></h1>
  <div class="flex">
    <%= render partial: "shared/badge", 
        locals: {key: "#{@habit.positive ? 'Building' : 'Breaking'} Since", value: Time.now.strftime("%m/%d/%y"), color: 'orange'}
       %>
    <div class="ml-2">
      <%= render partial: "shared/badge", locals: {key: 'Current Streak', value: days_since(@habit.last_reset), color: 'green'}%>
    </div>
  </div>
  <h2 class="mt-2">Actions</h2>
  <div class="flex content-center mb-2">
    <p class="my-0"><%= fraction_completed(@habit.actions) %> Completed</p>
    <%=link_to 'Update', edit_habit_path(@habit), class: 'btn-secondary btn-small my-auto ml-3'%>
  </div>
  <ul class="list-disc ml-6">
    <% @habit.actions.each do |action|%>
      <% unless action.description.to_s.strip.empty? %>
        <li class=<%=action.done ? "text-green-700" : "text-red-600"%>><%= action.description %></li>
      <% end %>
    <% end %>
  </ul>
  <div class="flex my-3">
    <h2 class="mb-0">Logs</h2>
    <%= link_to "Add Log", new_habit_log_path(@habit), class: "btn-secondary btn-small text-md ml-6 m-auto self-center"%>
  </div>
  <div>
    <%@habit.logs.each do |log|%>
      <%= link_to "#{log.created_at.strftime("%A, %b %d, %Y")}", habit_log_path(@habit, log)%>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Atomic Habit Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <nav>
      <ul class="flex bg-white py-4 shadow-md">
        <li class="mx-6">
          <%= link_to 'Atomic Habit Tracker', root_path, class: "text-blue-700 hover:text-blue-800" %>
        </li>
        <li class="mx-6">
          <%= link_to 'Habits', habits_path, class: "text-blue-700 hover:text-blue-800" %>
        </li>
        <li class="mx-6">
          <%= link_to 'New Habit', new_habit_path, class: "text-blue-700 hover:text-blue-800" %>
        </li>
      </ul>
    </nav>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/logs/new.html.erb
<div class="max-w-2xl m-auto mt-32 card">
  <h1>New Log Entry</h1>
  <h2>Habit: <%= @habit.name %></h1>
  <p class="text-gray-700"><%= Time.now.strftime("%A, %b %d, %Y") %></p>
  <%= form_with(model: [@habit, @habit.logs.build], local: true) do |form| %>
    <div>
      <%= form.text_area :text, class: "text-field", required: true%>
    </div>
    <div>
      <%= form.submit 'Save', class: "btn-primary mt-4 m-auto"%>
    </div>
  <% end %>
</div>

app/views/logs/show.html.erb
<div class="max-w-2xl m-auto mt-32 card">
  <h1>Log Entry for "<%= @habit.name %>"</h1>
  <p class="text-gray-700"><%= @log.created_at.strftime("%A, %b %d, %Y") %></p>
  <p><%= @log.text %> </p>
  <%= link_to 'Back', @habit %>
</div>

app/views/shared/_badge.html.erb
<div class="flex">
  <p class="bg-<%=color%>-500 rounded-l-md px-2 py-1 text-xs text-white"><%=key%></p>
  <p class="bg-<%=color%>-300 rounded-r-md px-2 py-1 text-xs "><%=value%></p>
</div>

app/views/welcome/index.html.erb
<div class="flex flex-col text-center mt-32 max-w-lg card m-auto">
  <h1>Atomic Habit Tracker</h1>
  <p>A simple application to help with building & breaking habits. Inspired by James Clear's <a href="https://jamesclear.com/atomic-habits">Atomic Habits</a>.</p>
  <%= link_to 'Get Started', new_habit_path, class: "btn-primary m-auto mt-4" %>
</div>